package tcpgraphic;

import java.awt.Graphics2D;

/**
 *
 * @author Tadashi
 */
public class JFrameGraphic extends javax.swing.JFrame {

    private Rendering rendering;
    private ViewContext context;
    
    private int mouseX = 0;
    private int mouseY = 0;
    
    
    /**
     * Creates new form JFrameGraphic
     */
    public JFrameGraphic() {
        initComponents();
        
        context = new ViewContext();
        context.setViewportWidth(this.getWidth());
        context.setViewportHeight(this.getHeight());
        context.setViewOriginX(this.getWidth() / 2);
        context.setViewOriginY(this.getHeight() / 2);
        
        rendering = new Rendering((Graphics2D) this.getGraphics(), context);
        rendering.start();
    }

    public Rendering getRendering() {
        return rendering;
    }

    public void setRendering(Rendering rendering) {
        this.rendering = rendering;
    }

    public ViewContext getContext() {
        return context;
    }

    public void setContext(ViewContext context) {
        this.context = context;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int deltaX = evt.getX() - mouseX;
        int deltaY = evt.getY() - mouseY;
        
        double viewOriginX = context.getViewOriginX();
        double viewOriginY = context.getViewOriginY();
        viewOriginX += deltaX;
        viewOriginY += deltaY;
        context.setViewOriginX(viewOriginX);
        context.setViewOriginY(viewOriginY);
        
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        double rotation = evt.getPreciseWheelRotation();
        double scaleFactor;
        if(rotation > 0){
            scaleFactor = 1 / 1.5;
        }else{
            scaleFactor = 1.5;
        }
        int scaleOriginX = evt.getX();
        int scaleOriginY = evt.getY();
        
        double viewOriginX = context.getViewOriginX();
        double viewOriginY = context.getViewOriginY();
        double viewScaleFactor = context.getViewScaleFactor();
        viewOriginX = (viewOriginX - scaleOriginX) * scaleFactor + scaleOriginX;
        viewOriginY = (viewOriginY - scaleOriginY) * scaleFactor + scaleOriginY;
        viewScaleFactor = viewScaleFactor * scaleFactor;
        context.setViewOriginX(viewOriginX);
        context.setViewOriginY(viewOriginY);
        context.setViewScaleFactor(viewScaleFactor);
    }//GEN-LAST:event_formMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGraphic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
